(function($){$.widget('depositphotos.depositFieldCounter',{options:{mode:'count',holder:'parent',min:0,max:0,prefix:'',format:'%count%'},_init:function(){this.$this=this.element;this._gatherParams();dp.core.binder(this.targets=this._gather(),this.handlers=this._handlers(),this.widgetFullName||this.widgetBaseClass)},_gather:function(){return{scope:{$field:this.$this,$counter:$('<i class="field-counter"></i>')}};},_handlers:function(){var _this=this;return{scope:{field:{handler:function(){_this.count(this.value);},events:['input','recount'],run:function(){this.addClass('has-counter');}},counter:{handler:function(e){if(e.type==='incorrect'){$(this).addClass('red');}
if(e.type==='reset'){$(this).removeClass('red');}},events:['incorrect','reset'],run:function(){if(_this.options.holder==='parent'){this.appendTo(_this.$this.parent());}else{this.appendTo((_this.options.holder instanceof jQuery)?_this.options.holder:$(_this.options.holder));}
this.trigger('recount');}}}};},count:function(value){var count=value.length||0;if(this.options.mode==='countdown'){count=this.options.max-count;}
var format=this.options.format.replace('%count%',count).replace('%max%',dp.tools.string(this.options.max)).replace('%prefix%',this.options.prefix);this.targets.scope.$counter.text(format);if(count>this.options.max||count<this.options.min||(this.options.mode==='countdown'&&count<0)){this.targets.scope.$counter.trigger('incorrect');}else{this.targets.scope.$counter.trigger('reset');}},_gatherParams:function(){var _this=this;var attributes=this.$this.get(0).attributes;var regex=/^data-/;var setParam=function(name,value){var names=name.split('-');if(value==='true'){value=true;}
if(value==='false'){value=false;}
if(typeof value==='string'&&value.indexOf(',')!==-1){value=value.split(',');}
if(names.length===2&&_this.options.hasOwnProperty(names[0])&&_this.options[names[0]].hasOwnProperty(names[1])){_this.options[names[0]][names[1]]=value;}
if(names.length===1&&_this.options.hasOwnProperty(names[0])){_this.options[names[0]]=value;}};for(var i=0;i<attributes.length;i++){if(attributes[i].nodeName.search(regex)>=0){setParam(attributes[i].nodeName.replace(regex,''),attributes[i].nodeValue);}
if(attributes[i].nodeName.toLowerCase()==='maxlength'){this.options.max=dp.tools.number(attributes[i].nodeValue);}}}})})(jQuery);
;